/** Static school catalogue used by Liste école + Fiche école. */

export const SCHOOLS = [
  {
    id: "esa",
    name: "École Spéciale d'Architecture – Paris",
    badge: ["ÉCOLE", "SPÉCIALE", "D'ARCHITECTURE", "PARIS"],
    city: "Paris, France",
    year: 1867,
    students: "1 200",
    domaine: "architecture",
    logo: "../assets/images/ecoles/logo-esa.png",
    thumb: "../assets/images/ecoles/thumb-school.png",
    hero: "../assets/images/ecoles/hero-esa.jpg",
    presentation: [
      "Fondée en 1867, l'École Spéciale d'Architecture (ESA) est l'une des plus anciennes écoles d'architecture privées de France. Située à Paris, elle forme des architectes capables de répondre aux enjeux contemporains de la ville, du logement et de l'environnement.",
      "L'école privilégie une pédagogie par le projet : ateliers de conception, critiques collectives et immersion progressive dans le monde professionnel. Les étudiants y développent une culture architecturale solide, alliant théorie, technique et pratique.",
      "Reconnue pour son ouverture internationale et son ancrage parisien, l'ESA accompagne chaque promotion vers le Diplôme d'État d'Architecture et des parcours de spécialisation en master.",
    ],
    formations: [
      {
        title: "Diplôme d'État d'Architecture (DE)",
        grade: "Grade Master",
        duration: "5 ans",
        desc: "Formation complète en architecture alliant conception, théorie, technique et pratique professionnelle.",
        icon: "../assets/icons/ic-ed-form-1.svg",
      },
      {
        title: "Master Architecture",
        grade: "Grade Master",
        duration: "2 ans",
        desc: "Approfondir vos compétences en conception architecturale et en projets urbains.",
        icon: "../assets/icons/ic-ed-form-2.svg",
      },
      {
        title: "Master Architecture & Transition écologique",
        grade: "Grade Master",
        duration: "2 ans",
        desc: "Former des architectes engagés pour une architecture durable et responsable.",
        icon: "../assets/icons/ic-ed-form-3.svg",
      },
      {
        title: "Mastère Spécialisé® Architecture & Innovation",
        grade: "Grade Mastère Spécialisé",
        duration: "1 an",
        desc: "Innover dans les matériaux, les usages et les technologies pour concevoir autrement.",
        icon: "../assets/icons/ic-ed-form-4.svg",
      },
    ],
    pointsForts: [
      "Pédagogie par le projet et ateliers intensifs",
      "Ancrage parisien et réseau professionnel",
      "Ouverture internationale et mobilités",
      "Spécialisations en transition écologique et innovation",
    ],
  },
  {
    id: "ensa-villette",
    name: "ENSA Paris-La Villette",
    badge: ["ENSA", "PARIS", "LA VILLETTE", ""],
    city: "Paris, France",
    year: 1969,
    students: "1 100",
    domaine: "architecture",
    logo: "../assets/images/ecoles/logo-ensa-villette.png",
    thumb: "../assets/images/ecoles/thumb-school.png",
    hero: "../assets/images/ecoles/hero-ensa-villette.jpg",
    presentation: [
      "L'École nationale supérieure d'architecture de Paris-La Villette (ENSAPLV) est l'une des plus grandes écoles d'architecture publiques de France. Elle accueille plus de mille étudiants au cœur du nord-est parisien.",
      "Son projet pédagogique explore la ville contemporaine, les territoires et les questions sociales liées à l'habitat. Les enseignements croisent conception, sciences humaines et techniques de la construction.",
      "L'école propose un environnement pluridisciplinaire, des partenariats institutionnels riches et une forte culture du débat architectural.",
    ],
    formations: [
      {
        title: "Diplôme d'État d'Architecture (DE)",
        grade: "Grade Master",
        duration: "5 ans",
        desc: "Cursus public d'architecte alliant conception, urbanité et culture du projet.",
        icon: "../assets/icons/ic-ed-form-1.svg",
      },
      {
        title: "Master Architecture & Ville",
        grade: "Grade Master",
        duration: "2 ans",
        desc: "Approfondir les enjeux urbains, paysagers et territoriaux contemporains.",
        icon: "../assets/icons/ic-ed-form-2.svg",
      },
      {
        title: "Master Architecture & Société",
        grade: "Grade Master",
        duration: "2 ans",
        desc: "Questionner le rôle social de l'architecte et les pratiques collaboratives.",
        icon: "../assets/icons/ic-ed-form-3.svg",
      },
      {
        title: "DSA Architecture & Patrimoine",
        grade: "DSA",
        duration: "2 ans",
        desc: "Se spécialiser dans l'intervention sur le bâti existant et le patrimoine.",
        icon: "../assets/icons/ic-ed-form-4.svg",
      },
    ],
    pointsForts: [
      "Grande école publique parisienne",
      "Approche urbaine et sociale affirmée",
      "Vaste communauté étudiante",
      "Partenariats culturels et institutionnels",
    ],
  },
  {
    id: "ensa-lyon",
    name: "ENSA Lyon",
    badge: ["ENSA", "LYON", "", ""],
    city: "Lyon, France",
    year: 1968,
    students: "1 000",
    domaine: "architecture",
    logo: "../assets/images/ecoles/logo-ensa-lyon.png",
    thumb: "../assets/images/ecoles/thumb-school.png",
    hero: "../assets/images/ecoles/hero-ensa-lyon.jpg",
    presentation: [
      "L'ENSA Lyon forme des architectes au carrefour de la recherche, de la technique et du projet. Installée dans la métropole lyonnaise, elle tire parti d'un territoire dynamique et d'un écosystème d'innovation.",
      "Les étudiants y construisent une démarche critique sur l'architecture, le paysage et la fabrication de la ville, avec une attention particulière aux transitions écologiques.",
      "L'école valorise l'expérimentation, les workshops et les collaborations avec les acteurs locaux du cadre bâti.",
    ],
    formations: [
      {
        title: "Diplôme d'État d'Architecture (DE)",
        grade: "Grade Master",
        duration: "5 ans",
        desc: "Formation d'architecte publique tournée vers le projet et le territoire.",
        icon: "../assets/icons/ic-ed-form-1.svg",
      },
      {
        title: "Master Architecture & Transitions",
        grade: "Grade Master",
        duration: "2 ans",
        desc: "Explorer les transitions énergétiques, climatiques et constructives.",
        icon: "../assets/icons/ic-ed-form-3.svg",
      },
      {
        title: "Master Architecture & Paysage",
        grade: "Grade Master",
        duration: "2 ans",
        desc: "Articuler architecture, paysage et aménagement des milieux.",
        icon: "../assets/icons/ic-ed-form-2.svg",
      },
      {
        title: "HMONP",
        grade: "Habilitation",
        duration: "1 an",
        desc: "Préparer l'exercice de la maîtrise d'œuvre en nom propre.",
        icon: "../assets/icons/ic-ed-form-4.svg",
      },
    ],
    pointsForts: [
      "Ancrage métropolitain lyonnais",
      "Focus transitions et territoires",
      "Culture de l'expérimentation",
      "Liens forts avec la recherche",
    ],
  },
  {
    id: "strate",
    name: "Strate École de Design",
    badge: ["STRATE", "ÉCOLE", "DE DESIGN", "PARIS"],
    city: "Paris, France",
    year: 1993,
    students: "800",
    domaine: "architecture",
    logo: "../assets/images/ecoles/logo-strate.png",
    thumb: "../assets/images/ecoles/thumb-school.png",
    hero: "../assets/images/ecoles/hero-strate.jpg",
    presentation: [
      "Strate École de Design forme des designers capables d'imaginer des produits, services et expériences pour un monde en mutation. L'école cultive une approche humaine, créative et stratégique du design.",
      "À travers des projets concrets avec des entreprises et des institutions, les étudiants apprennent à allier dessin, prototypage, recherche utilisateur et innovation.",
      "Le campus parisien offre un environnement stimulant, au croisement du design produit, du design d'interaction et du design d'espace.",
    ],
    formations: [
      {
        title: "Design Produit",
        grade: "Grade Master",
        duration: "5 ans",
        desc: "Concevoir des objets et systèmes utiles, désirables et responsables.",
        icon: "../assets/icons/ic-ed-form-1.svg",
      },
      {
        title: "Design d'Interaction",
        grade: "Grade Master",
        duration: "5 ans",
        desc: "Imaginer des expériences numériques et des interfaces centrées utilisateur.",
        icon: "../assets/icons/ic-ed-form-2.svg",
      },
      {
        title: "Design Transport & Mobilité",
        grade: "Grade Master",
        duration: "5 ans",
        desc: "Repenser les mobilités de demain et les espaces associés.",
        icon: "../assets/icons/ic-ed-form-3.svg",
      },
      {
        title: "Mastère Design & Innovation",
        grade: "Mastère",
        duration: "1 an",
        desc: "Accélérer une spécialisation en stratégie de design et innovation.",
        icon: "../assets/icons/ic-ed-form-4.svg",
      },
    ],
    pointsForts: [
      "Pédagogie par projets réels",
      "Culture design & innovation",
      "Partenariats entreprises",
      "Campus créatif en Île-de-France",
    ],
  },
  {
    id: "ensa-malaquais",
    name: "ENSA Paris-Malaquais",
    badge: ["ENSA", "PARIS", "MALAQUAIS", ""],
    city: "Paris, France",
    year: 1969,
    students: "950",
    domaine: "architecture",
    logo: "../assets/images/ecoles/logo-malaquais.png",
    thumb: "../assets/images/ecoles/thumb-school.png",
    hero: "../assets/images/ecoles/hero-malaquais.jpg",
    presentation: [
      "L'ENSA Paris-Malaquais occupe une place singulière dans le paysage des écoles d'architecture françaises. Elle cultive une tradition d'exigence intellectuelle et de liberté pédagogique.",
      "Située à Paris, l'école encourage la recherche par le projet, les expérimentations critiques et le dialogue entre disciplines artistiques, techniques et scientifiques.",
      "Les étudiants y développent une voix architecturale personnelle, nourrie par l'histoire, la théorie et la pratique contemporaine.",
    ],
    formations: [
      {
        title: "Diplôme d'État d'Architecture (DE)",
        grade: "Grade Master",
        duration: "5 ans",
        desc: "Cursus exigeant tourné vers la culture du projet et la recherche.",
        icon: "../assets/icons/ic-ed-form-1.svg",
      },
      {
        title: "Master Architecture & Théorie",
        grade: "Grade Master",
        duration: "2 ans",
        desc: "Approfondir les fondements théoriques et critiques de l'architecture.",
        icon: "../assets/icons/ic-ed-form-2.svg",
      },
      {
        title: "Master Architecture & Expérimentation",
        grade: "Grade Master",
        duration: "2 ans",
        desc: "Explorer des démarches expérimentales de conception et de fabrication.",
        icon: "../assets/icons/ic-ed-form-4.svg",
      },
      {
        title: "HMONP",
        grade: "Habilitation",
        duration: "1 an",
        desc: "Accéder à l'exercice de la maîtrise d'œuvre en son nom propre.",
        icon: "../assets/icons/ic-ed-form-3.svg",
      },
    ],
    pointsForts: [
      "Exigence intellectuelle et créative",
      "Culture du débat architectural",
      "Position centrale à Paris",
      "Recherche par le projet",
    ],
  },
];

export function getSchoolById(id) {
  return SCHOOLS.find((s) => s.id === id) || SCHOOLS[0];
}
